apiVersion: apps/v1
kind: Deployment

metadata:
  name: discord-bot

spec:
  replicas: 1

  selector:
    matchLabels:
      app: discord-bot

  template:
    metadata:
      labels:
        app: discord-bot

    spec:
      containers:
      - name: discord-bot
        image: ken900809/discord-bot:latest
        imagePullPolicy: Always

        ports:
          - containerPort: 8080

      envFrom:
        - secretRef:
            name: discord-bot-secret