CREATE TABLE IF NOT EXISTS song_embeddings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artist VARCHAR(512) NOT NULL,
    song VARCHAR(512) NOT NULL,
    link VARCHAR(1024) NOT NULL,
    chunk_index INTEGER NOT NULL,
    chunk_text TEXT NOT NULL,
    embedding VECTOR(768) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_song_embeddings_link_chunk
        UNIQUE (link, chunk_index),
    CONSTRAINT ck_song_embeddings_chunk_index
        CHECK (chunk_index >= 0)
);

CREATE INDEX IF NOT EXISTS idx_song_embeddings_artist_song
    ON song_embeddings (artist, song);
